---
dist: trusty
language: node_js

sudo: false

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache # includes bowers cache

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --pure-lockfile

script:
  - yarn test

after_success:
  - cat ./coverage/report-lcov/lcov.info | ./node_modules/coveralls/bin/coveralls.js